### PR TITLE
[DRAFT] Move from ListingsController#index -> ContributionsController#index

### PR DESCRIPTION
**Pull request by maebeale**
- Update contributions index and view to current listings index and view
- Point Vue listings.json -> contributions.json
- Remove listings_index view and endpoint (and replace listings index with contents)
- Change helper path name to use contributions_path

It seems to (almost) just work (TM)!

### CODE REVIEW

**Comment by h-m-m** [comment]
Closing. Resolved by #402 with some bugfixes in #459 and #463

**Comment by maebeale** [comment]
Listings index still isn't railsy tho?

**Comment by maebeale** [comment]
Ok if I submit an update to this PR to complete it?

**Comment by h-m-m** [comment]
@maebeale good point. Would it be easier to do that in a separate PR?

**Comment by maebeale** [comment]
ok

**Comment by maebeale** [comment]
i was seeing it as part of the same scope, per orig to-do list, but, yup! i'll do in another PR

**Pull request closed without merging**
