### PR TITLE
Hide navbar on forms, public_controller indexes, and thank you

### PR DESCRIPTION
**Pull request by maebeale**
- hide_navbar for forms, public_controller indexes, and form submission thank_you page
- show "Return to admin" if user signed in

### CODE REVIEW

**Comment by maebeale** [comment]
@exbinary you ok w this solution?

**Comment by maebeale** [comment]
A separate help?

**Comment by maebeale** [comment]
I was thinking yes re nav. Do you agree?

**Comment by exbinary** [comment]
> A separate help?

Oops, sorry! "Would a separate _layout_ help ..."

**Comment by exbinary** [comment]
> I was thinking yes re nav. Do you agree?

I think that makes sense for all our current groups where the forms are the only things `People` see. I could see a case in the future, maybe with p2p, where more of the app is visible to the public, including some navigation; in that case, it would be better to have the form use the same skin. But we can solve for that when we have to.

**Comment by maebeale** [comment]
Yes, but I thought you didn't want to do it that way. ? Maybe I'm
misremembering.

**Comment by maebeale** [comment]
k!

**Comment by maebeale** [comment]
will add layout back in

**Comment by maebeale** [comment]
k. have added back in the layout we used to have in there called "public" -- bc there are public-facing pages where we do want to have the navbar -- and instead named it without_navbar.

this seem good, @exbinary ?

**Pull request merged**
